site_name: The Road to Zero
site_url: https://faisalmemon.github.io/the-road-to-zero/
theme: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
repo_url: https://github.com/faisalmemon/the-road-to-zero/
nav:
    - Home: index.md
    - About: Author.md
    - Introduction: Introduction.md
    - Zero Day: ZeroDay.md
    - The Hammer: Hammer.md
    - Mach Programming: Mach.md
    - Kernel Debugging: KernelDebugging.md
    - Jailbreak Setup: JailbreakSetup.md
    - Inspecting Mobile Safari: InspectingMobileSafari.md
    - Bibliography: Bibliography.md

