site_name: The Road to Zero
site_url: https://faisalmemon.github.io/the-road-to-zero/
theme: material
repo_url: https://github.com/faisalmemon/the-road-to-zero/
nav:
    - Home: index.md
    - About: Author.md
    - Introduction: Introduction.md
    - Zero Day: ZeroDay.md
    - The Hammer: Hammer.md
    - Mach: Mach.md
    - Kernel Debugging: KernelDebugging.md
    - Booting a Development Kernel: BootingDevelopmentKernel.md
    - Jailbreak Setup: JailbreakSetup.md
    - Bibliography: Bibliography.md

