site_name: The Road to Zero
site_url: https://faisalmemon.github.io/the-road-to-zero/
theme: material
repo_url: https://github.com/faisalmemon/the-road-to-zero/
nav:
    - Home: index.md
    - About: about.md
    - Disclaimer1: Disclaimer_heading.md
    - Disclaimer2: Disclaimer_body.md
    - Trademarks: trademarks.md
    - Preface1: Preface_heading.md
    - Preface2: Preface_body.md
    - Acknowledgements1: Acknowledgements_heading.md
    - Acknowledgements2: Acknowledgements_body.md
    - Introduction1: Introduction_heading.md
    - Introduction2: Introduction_body.md
    - ZeroDay: ZeroDay.md
    - Hammer: Hammer.md
    - Mach: Mach.md
    - KernelDebugging: KernelDebugging.md
    - BootingDevelopmentKernel: examples/boot_dev_kernel/BootingDevelopmentKernel.md
    - JailbreakSetup: JailbreakSetup.md
    - Bibliography: Bibliography.md

