site_name: The Road to Zero
site_url: https://faisalmemon.github.io/the-road-to-zero/
theme: material
repo_url: https://github.com/faisalmemon/the-road-to-zero/
nav:
    - Home: index.md
    - About: Author.md
    - Introduction: Introduction.md
    - ZeroDay: ZeroDay.md
    - Hammer: Hammer.md
    - Mach: Mach.md
    - KernelDebugging: KernelDebugging.md
    - BootingDevelopmentKernel: examples/boot_dev_kernel/BootingDevelopmentKernel.md
    - JailbreakSetup: JailbreakSetup.md
    - Bibliography: Bibliography.md

